version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clients-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hle82tq63qlj"
s3_prefix = "clients-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
